version: "3"

# The same as
# $ docker build -f Dockerfile.dev --tag=zhang/react:1.0 .
# $ docker run -it -d -p 3000:3000 -v /app/node_modules -v ./:/app zhang/react:1.0 

services: 
  react_app:
    build: 
      context: .
      dockerfile: Dockerfile.dev

    ports: 
      - 3000:3000

    volumes: 
      # according to the Dockerfile. where is the local file.
      # 
      - /app/node_modules
      - ./:/app/
